const path = require('path');

module.exports = {
  base: '/interview-practice/',
  title: '前端面试刷题',
  description: '每日半小时，巩固基础，助力面试',
  dest: path.resolve(__dirname, '../../docs'),
  themeConfig: {
    nav: [
      { text: 'github', link: 'https://github.com/iloveyou11/interview-practice' },
      { text: '个人博客', link: 'https://github.com/iloveyou11/learning-blog' }
    ],
    sidebarDepth: 0,
    sidebar: [
      {
        "title": "js系列",
        "collapsable": true,
        "sidebarDepth": 1,
        "children": [
          "/js/1",
          "/js/2",
          "/js/3",
          "/js/4",
          "/js/5",
          "/js/6",
          "/js/7",
          "/js/8",
          "/js/9",
          "/js/10",
          "/js/11",
          "/js/12",
          "/js/13",
          "/js/14",
          "/js/15",
          "/js/16",
          "/js/17",
          "/js/18",
          "/js/19",
          "/js/20",
          "/js/21",
          "/js/22",
          "/js/23",
          "/js/24",
          "/js/25",
          "/js/26",
          "/js/27",
          "/js/28",
          "/js/29",
          "/js/30",
          "/js/31",
          "/js/32",
          "/js/33",
          "/js/34",
          "/js/35",
          "/js/36",
          "/js/37",
          "/js/38",
          "/js/39",
          "/js/40",
          "/js/41",
          "/js/42",
          "/js/43",
          "/js/44",
          "/js/45",
          "/js/46",
          "/js/47"
        ]
      },
      {
        "title": "html/css系列",
        "collapsable": true,
        "sidebarDepth": 1,
        "children": [
          "/htmlcss/1",
          "/htmlcss/2",
          "/htmlcss/3",
          "/htmlcss/4",
          "/htmlcss/5",
          "/htmlcss/6",
          "/htmlcss/7",
          "/htmlcss/8",
          "/htmlcss/9",
          "/htmlcss/10",
          "/htmlcss/11",
          "/htmlcss/12",
          "/htmlcss/13",
          "/htmlcss/14",
          "/htmlcss/15",
          "/htmlcss/16",
          "/htmlcss/17",
          "/htmlcss/18",
          "/htmlcss/19",
          "/htmlcss/20",
          "/htmlcss/21",
          "/htmlcss/22",
          "/htmlcss/23",
          "/htmlcss/24",
          "/htmlcss/25"
        ]
      },
      {
        "title": "浏览器系列",
        "collapsable": true,
        "sidebarDepth": 1,
        "children": [
          "/browser/1",
          "/browser/2",
          "/browser/3",
          "/browser/4",
          "/browser/5",
          "/browser/6",
          "/browser/7",
          "/browser/8",
          "/browser/9",
          "/browser/10"
        ]
      },
      {
        "title": "框架系列",
        "collapsable": true,
        "sidebarDepth": 1,
        "children": [
          "/framework/1",
          "/framework/2",
          "/framework/3",
          "/framework/4",
          "/framework/5",
          "/framework/6",
          "/framework/7",
          "/framework/8",
          "/framework/9",
          "/framework/10",
          "/framework/11"
        ]
      },
      {
        "title": "node系列",
        "collapsable": true,
        "sidebarDepth": 1,
        "children": [
          "/node/1",
          "/node/2",
          "/node/3"
        ]
      },
      {
        "title": "算法系列",
        "collapsable": true,
        "sidebarDepth": 1,
        "children": [
          "/algorithm/1",
          "/algorithm/2",
          "/algorithm/3",
          "/algorithm/4",
          "/algorithm/5",
          "/algorithm/6",
          "/algorithm/7",
          "/algorithm/8",
          "/algorithm/9",
          "/algorithm/10",
          "/algorithm/11",
          "/algorithm/12",
          "/algorithm/13",
          "/algorithm/14",
          "/algorithm/15",
          "/algorithm/16",
          "/algorithm/17",
          "/algorithm/18",
          "/algorithm/19",
          "/algorithm/20",
          "/algorithm/21"
        ]
      },
      {
        "title": "网络系列",
        "collapsable": true,
        "sidebarDepth": 1,
        "children": [
          "/network/1",
          "/network/2",
          "/network/3",
          "/network/4",
          "/network/5",
          "/network/6",
          "/network/7",
          "/network/8",
          "/network/9",
          "/network/10",
          "/network/11",
          "/network/12",
          "/network/13",
          "/network/14",
          "/network/15",
          "/network/16",
          "/network/17",
          "/network/18",
          "/network/19",
          "/network/20",
          "/network/21",
          "/network/22",
          "/network/23",
          "/network/24"
        ]
      }
    ]
  }
};